FROM buildpack-deps:bookworm

COPY *.patch /usr/src/perl/
WORKDIR /usr/src/perl

RUN true \
    && curl -SL https://www.cpan.org/src/5.0/perl-5.26.3.tar.gz -o perl-5.26.3.tar.gz \
    && echo 'b75ae40de8292fa53021b35eb3552fcaf65d7891ce4c5b6668d665cb0233c493 *perl-5.26.3.tar.gz' | sha256sum -c - \
    && tar --strip-components=1 -xaf perl-5.26.3.tar.gz -C /usr/src/perl \
    && rm perl-5.26.3.tar.gz \
    && cat *.patch | patch -p1 \
    && gnuArch="$(dpkg-architecture --query DEB_BUILD_GNU_TYPE)" \
    && archBits="$(dpkg-architecture --query DEB_BUILD_ARCH_BITS)" \
    && archFlag="$([ "$archBits" = '64' ] && echo '-Duse64bitall' || echo '-Duse64bitint')" \
    && ./Configure -Darchname="$gnuArch" "$archFlag" -Duseshrplib -Dvendorprefix=/usr/local  -des \
    && make -j$(nproc) \
    && TEST_JOBS=$(nproc) make test_harness \
    || true \
    && make install \
    && cd /usr/src \
    && curl -LO https://www.cpan.org/authors/id/M/MI/MIYAGAWA/App-cpanminus-1.7047.tar.gz \
    && echo '963e63c6e1a8725ff2f624e9086396ae150db51dd0a337c3781d09a994af05a5 *App-cpanminus-1.7047.tar.gz' | sha256sum -c - \
    && tar -xzf App-cpanminus-1.7047.tar.gz && cd App-cpanminus-1.7047 && perl bin/cpanm . && cd /root \
    && true \
    && rm -fr ./cpanm /root/.cpanm /usr/src/perl /usr/src/App-cpanminus-1.7047* /tmp/*

WORKDIR /

CMD ["perl5.26.3","-de0"]
